// ========================================
// PORTFOLIO DATA - YOUR CENTRALIZED DASHBOARD
// ========================================
// This file contains ALL your portfolio content in one place.
// Generated by Portfolio Dashboard

const portfolioData = {
  "siteVersion": "v1.3.2",
  "personal": {
    "name": "Ahmed Maher",
    "profession": "Computer Science Student & Systems Tinkerer",
    "tagline": "Repurposing Legacy Hardware & Exploring System Security",
    "background": "Linux Enthusiast | Hardware Revivalist | Security Researcher",
    "bio": "I’m the kind of person who can’t see a piece of old tech without wondering how to bring it back to life. My journey started with 'modding' a school tablet and fixing family phones, and it led me to building full-scale home servers from what others called 'junk' hardware.\n\nCurrently a 3rd-year Computer Science student at HTI, I refuse to be boxed into a single 'track.' I dive into Backend, explore Cyber Security, and mess around with Video Editing. To me, it’s not about the title; it’s about solving problems and understanding how technology works under the hood. If a system needs a workaround or an idea needs to be executed smartly and on a budget—I’m the one for the job.",
    "logo": "Image/Logo Without BG.png",
    "profileImage": "Image/Portfolio img.jpg",
    "email": "anshtaun00@gmail.com",
    "github": "MedoMaher01",
    "linkedin": "x0maro",
    "siteUrl": "https://medomaher01.github.io/Portfolio-Project/index.html",
    "description": "Professional portfolio of Ahmed Maher, a passionate Software Developer specializing in Full-Stack Development & Web Solutions.",
    "keywords": "portfolio, web developer, projects, Ahmed Maher, Software Developer, Full-Stack Development"
  },
  "projectCategories": {
    "system-architecture": {
      "title": "System Architecture",
      "icon": "💻",
      "description": "Reviving old hardware, building home servers, and Linux system administration.",
      "projects": [
        {
          "id": "project-phoenix-homelab",
          "title": "Project Phoenix: Transforming Old Android into a Linux Home Server",
          "subtitle": "An engineering experiment to upcycle e-waste into a fully functional 24/7 Home Lab & NAS",
          "description": "Instead of throwing away my old Android tablet, I decided to challenge myself: Can this become a real server?\n\nI rooted the device, replaced the Android restrictions with a full Linux environment (Ubuntu), and built a complete Home Lab. Now, this 'e-waste' handles my entire network's ad-blocking, stores my files as a NAS, and runs my web projects—all powered by a single USB charger. It’s proof that with the right optimization, hardware limitations are just a mindset.",
          "icon": "Image\\logo Project Phoenix.png",
          "techStack": [
            "Linux Administration",
            "Bash Scripting",
            "Networking (DNS & VPN)",
            "Docker / Containers",
            "AdGuard Home",
            "Samba (NAS)",
            "Apache Web Server",
            "HTML/CSS/JS (Dashboard)"
          ],
          "links": [],
          "sections": [
            {
              "type": "heading",
              "level": 2,
              "value": "The \"Why\" Behind The Project"
            },
            {
              "type": "text",
              "value": "I wanted to understand Linux networking and server management at a deeper level. Buying a Raspberry Pi was the easy option, but engineering a solution using existing hardware was the real challenge. I had to solve kernel-level issues, manage strict Android permissions, and optimize resources for a device with limited RAM.",
              "bold": false,
              "italic": false,
              "fontSize": "medium"
            },
            {
              "type": "heading",
              "level": 2,
              "value": "What I Built & Achieved"
            },
            {
              "type": "list",
              "ordered": false,
              "items": [
                "Total Control: Gained root access and deployed Ubuntu via Linux Deploy.",
                "Network Security: Configured AdGuard Home to block ads/trackers for all devices at home.",
                "Cloud Storage: Turned the tablet into a NAS using Samba to share files between my laptop and phone.",
                "Remote Access: Set up a secure VPN tunnel using Tailscale to access my server from anywhere safely.",
                "Custom Interface: coded a responsive dark-mode dashboard to monitor everything."
              ],
              "nestedItems": [
                {
                  "text": "Total Control: Gained root access and deployed Ubuntu via Linux Deploy.",
                  "level": 0
                },
                {
                  "text": "Network Security: Configured AdGuard Home to block ads/trackers for all devices at home.",
                  "level": 0
                },
                {
                  "text": "Cloud Storage: Turned the tablet into a NAS using Samba to share files between my laptop and phone.",
                  "level": 0
                },
                {
                  "text": "Remote Access: Set up a secure VPN tunnel using Tailscale to access my server from anywhere safely.",
                  "level": 0
                },
                {
                  "text": "Custom Interface: coded a responsive dark-mode dashboard to monitor everything.",
                  "level": 0
                }
              ]
            },
            {
              "type": "heading",
              "level": 4,
              "value": "My custom-built dashboard running on the tablet server"
            },
            {
              "type": "image",
              "src": "Image\\Screenshot  (1).png",
              "alt": "Image"
            },
            {
              "type": "image",
              "src": "Image\\Screenshot  (2).png",
              "alt": "Image"
            },
            {
              "type": "code",
              "language": "Bash",
              "value": "# Example: Restarting the server services\nservice apache2 restart\nservice smbd restart\ntailscale up --advertise-exit-node"
            }
          ]
        }
      ]
    },
    "cyber-security": {
      "title": "Cyber Security",
      "icon": "🛡️",
      "description": "Documenting TryHackMe challenges, Kali Linux experiments, and system vulnerability research.",
      "projects": []
    },
    "software-dev": {
      "title": "Software Development",
      "icon": "🚀",
      "description": "Building projects with C++ and Python, focusing on clean code and core fundamentals.",
      "projects": [
        {
          "id": "web-portfolio",
          "title": "Personal Portfolio Website",
          "subtitle": "Responsive portfolio showcasing skills and projects",
          "sections": [
            {
              "type": "heading",
              "level": 2,
              "value": "📋 Overview"
            },
            {
              "type": "text",
              "value": "A modern, fully responsive portfolio website built from scratch using HTML5, CSS3, and vanilla JavaScript. This project showcases my skills and projects in a professional, user-friendly interface."
            },
            {
              "type": "heading",
              "level": 2,
              "value": "✨ Key Features"
            },
            {
              "type": "list",
              "ordered": false,
              "items": [
                "Interactive timeline showcasing professional journey",
                "Projects gallery organized by skill categories",
                "Smooth scroll animations and transitions",
                "Comprehensive SEO optimization",
                "Mobile-first responsive design",
                "Accessibility features (ARIA labels, semantic HTML)",
                "Dynamic content rendering from centralized data file"
              ]
            },
            {
              "type": "heading",
              "level": 2,
              "value": "🎯 Design Philosophy"
            },
            {
              "type": "text",
              "value": "The design follows mobile-first principles with a strong focus on user experience and accessibility. Every element is carefully crafted to ensure smooth navigation and clear information hierarchy."
            },
            {
              "type": "heading",
              "level": 3,
              "value": "Color Scheme"
            },
            {
              "type": "text",
              "value": "The website uses a professional color palette with high contrast ratios to ensure readability and visual appeal across all devices."
            },
            {
              "type": "heading",
              "level": 2,
              "value": "💻 Technical Implementation"
            },
            {
              "type": "text",
              "value": "The project is built with vanilla JavaScript to demonstrate core web development skills without relying on frameworks. Here's an example of the dynamic rendering system:"
            },
            {
              "type": "code",
              "language": "javascript",
              "value": "// Dynamic project rendering\nfunction renderProjectCard(project) {\n  return `\n    <article class=\"project-card\">\n      <h3>${project.title}</h3>\n      <p>${project.subtitle}</p>\n      <div class=\"tech-stack\">\n        ${project.techStack.map(tech => \n          `<span class=\"badge\">${tech}</span>`\n        ).join('')}\n      </div>\n    </article>\n  `;\n}"
            },
            {
              "type": "heading",
              "level": 2,
              "value": "📊 Project Structure"
            },
            {
              "type": "list",
              "ordered": true,
              "items": [
                "index.html - Main landing page",
                "my-journey.html - Interactive timeline page",
                "projects.html - Projects showcase page",
                "project.html - Individual project details",
                "data.js - Centralized content management",
                "render.js - Dynamic rendering engine",
                "styles.css - Main stylesheet"
              ]
            },
            {
              "type": "heading",
              "level": 2,
              "value": "🚀 Performance Optimization"
            },
            {
              "type": "text",
              "value": "Several optimization techniques were implemented to ensure fast loading times:"
            },
            {
              "type": "list",
              "ordered": false,
              "items": [
                "Lazy loading for images and videos",
                "Minified CSS and JavaScript files",
                "Optimized image formats and sizes",
                "Efficient DOM manipulation strategies",
                "Intersection Observer for scroll animations"
              ]
            },
            {
              "type": "heading",
              "level": 2,
              "value": "📱 Responsive Design"
            },
            {
              "type": "text",
              "value": "The website is fully responsive and optimized for all screen sizes. The mobile navigation uses a hamburger menu, and all content adapts seamlessly to different viewports."
            },
            {
              "type": "heading",
              "level": 2,
              "value": "🎓 What I Learned"
            },
            {
              "type": "text",
              "value": "This project enhanced my understanding of:"
            },
            {
              "type": "list",
              "ordered": false,
              "items": [
                "Semantic HTML5 structure and best practices",
                "CSS Grid and Flexbox for modern layouts",
                "Vanilla JavaScript DOM manipulation",
                "SEO optimization techniques",
                "Web accessibility standards (WCAG)",
                "Performance optimization strategies"
              ]
            }
          ],
          "description": "A modern, fully responsive portfolio website built from scratch using HTML5, CSS3, and vanilla JavaScript. Features include an interactive timeline showcasing my professional journey, a projects gallery organized by skills, smooth scroll animations, and comprehensive SEO optimization. The design follows mobile-first principles with a focus on accessibility and user experience.",
          "techStack": [
            "HTML5",
            "CSS3",
            "JavaScript",
            "Responsive Design",
            "SEO"
          ],
          "links": [
            {
              "type": "github",
              "url": "https://github.com/MedoMaher01/Portfolio-Project",
              "label": "View Code"
            },
            {
              "type": "demo",
              "url": "https://medomaher01.github.io/Portfolio-Project/index.html",
              "label": "Live Demo"
            }
          ],
          "icon": "Image/Logo.png"
        }
      ]
    },
    "mobile-modding": {
      "title": "Mobile Modding",
      "icon": "📱",
      "description": "Hardware repairs, custom ROMs, and advanced Android automation via Termux.",
      "projects": []
    },
    "innovation": {
      "title": "Business & Innovation",
      "icon": "💡",
      "description": "Exploring entrepreneurship and digital transformation through programs like innovEgypt (ITIDA).",
      "projects": []
    },
    "the-lab": {
      "title": "The Lab",
      "icon": "🧪",
      "description": "A collection of experimental scripts and works-in-progress from my daily tinkering.",
      "projects": []
    }
  },
  "timeline": [
    {
      "date": "2013",
      "title": "More Than Just Games",
      "description": "Got my first PC. While everyone was gaming, I was busy asking: \"How does this work? What happens if I change this setting?",
      "icon": "🖥️",
      "category": "milestone"
    },
    {
      "date": "2016",
      "title": "The Digital Window",
      "description": "Middle school started, and we finally got internet at home. The PC became more than a machine; it was my window to an endless world of learning.",
      "icon": "🌐",
      "category": "exploration"
    },
    {
      "date": "2019",
      "title": "Breaking the System",
      "description": "In High School, the school tablet was my first real challenge. \"How do I get this out of the restricted system?\" That was my first true taste of hacking and system logic.",
      "icon": "🔓",
      "category": "academic"
    },
    {
      "date": "2020",
      "title": "Linux in My Pocket",
      "description": "Discovered Termux and managed to run Kali Linux on my phone. It changed my perspective of mobile devices from simple gadgets to powerful programming tools.",
      "icon": "🐧",
      "category": "exploration"
    },
    {
      "date": "2022",
      "title": "Solid Foundations",
      "description": "Decided to go academic. I started with C++ to understand the low-level fundamentals that separate a 'coder' from a real Engineer.",
      "icon": "📚",
      "category": "self-learning"
    },
    {
      "date": "2023 - Present",
      "title": "The HTI Exploration",
      "description": "Joined HTI and started a deep dive into everything—Backend, Security, and Entrepreneurship. Certifications from TryHackMe and innovEgypt (ITIDA) are just markers on a path of constant exploration.",
      "icon": "🚀",
      "category": "academic"
    }
  ],
  "categories": {
    "milestone": {
      "label": "Milestone",
      "color": "#007bff"
    },
    "self-learning": {
      "label": "Self-Learning",
      "color": "#28a745"
    },
    "academic": {
      "label": "Academic",
      "color": "#6f42c1"
    },
    "exploration": {
      "label": "Exploration",
      "color": "#fd7e14"
    },
    "achievement": {
      "label": "Achievement",
      "color": "#ffc107"
    }
  }
};

// ========================================
// HELPER FUNCTIONS
// ========================================

// Get all projects from all categories as a flat array
function getAllProjects() {
  const categories = portfolioData.projectCategories;
  return Object.values(categories).flatMap(cat => cat.projects);
}

// Get project by ID (searches across all categories)
function getProjectById(projectId) {
  return getAllProjects().find(p => p.id === projectId);
}

// Get projects by category key
function getProjectsByCategory(categoryKey) {
  if (categoryKey === 'all') return getAllProjects();
  return portfolioData.projectCategories[categoryKey]?.projects || [];
}

// Get timeline events by category
function getTimelineByCategory(category) {
  return portfolioData.timeline.filter(e => e.category === category);
}

// Generate project link for timeline
function getProjectLink(projectId) {
  const project = getProjectById(projectId);
  if (!project) return null;
  return {
    url: `project.html?id=${projectId}`,
    title: project.title
  };
}